# -*- coding: utf-8 -*-
"""dvp_progX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4unzJYI002rfoAx2URZSGgkE5sKHfqi

10) a) dollar vs rupee graph using plotly and pandas
"""

import pandas as pd
import plotly.express as px

dollar_conv = pd.read_csv('CUR_DLR_INR.csv')

fig = px.line(dollar_conv, x='DATE', y='RATE', title='Dollar vs Rupee')
fig.show()

"""10) b) creating map using plotly libraries"""

import plotly.express as px

import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder_with_codes.csv')

fig = px.choropleth(data, locations='iso_alpha', color='gdpPercap',
                    hover_name='country', projection='natural earth', title='GDP per Capita by Country')

fig.show()

from google.colab import files
uploaded = files.upload()